Assignment2/Models/ErrorViewModel.cs
using System;

namespace Assignment2.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Assignment2/Models/ISerialNumbersData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Assignment2.Models
{
    public interface ISerialNumbersData
    {
        IEnumerable<string> GetAll();
        bool VerifySerialNumber(string serialNumber);
    }
}

Assignment2/Models/ISubmissionData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MyClassLibrary;

namespace Assignment2.Models
{
    public interface ISubmissionData
    {

        IEnumerable<Submission> GetAll();

        void AddSubmission(Submission sub);

        bool VerifyNewSubmission(string serialNumber);
    }
}

Assignment2/Models/SerialNumbersData.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Threading.Tasks;
using System.Xml;
using System.Xml.Serialization;

namespace Assignment2.Models
{
    public class SerialNumbersData : ISerialNumbersData
    {

        private List<string> _serialNumbers;

        protected const string filePath = @"..\MyClassLibrary\serialNumbers.bin";

        public SerialNumbersData()
        {
            _serialNumbers = new List<string>();
            AddSerialNumbers();
        }

        public IEnumerable<string> GetAll()
        {
            using (Stream stream = File.Open(filePath, FileMode.Open))
            {
                var binaryFormatter = new BinaryFormatter();

                var otherList = (List<string>)binaryFormatter.Deserialize(stream);
                return otherList;
            }
        }

        public bool VerifySerialNumber(string serialNumber)
        {
            return GetAll().Contains(serialNumber);
        }

        protected Random random = new Random();
        protected string RandomSerialNumber(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        private void AddSerialNumbers()
        {
            for (var i = 0; i < 100; i++)
            {
                _serialNumbers.Add(RandomSerialNumber(16));
            }
            using (Stream stream = File.Open(filePath, FileMode.Create))
            {
                var binaryFormatter = new BinaryFormatter();
                binaryFormatter.Serialize(stream, _serialNumbers);
                stream.Close();
            }
        }
    }
}

Assignment2/Models/SubmissionData.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.Serialization.Formatters.Binary;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using MyClassLibrary;

namespace Assignment2.Models
{
    public class SubmissionData : ISubmissionData
    {
        private List<Submission> _submissions;

        protected const string filePath = @"..\MyClassLibrary\submissions.bin";

        public SubmissionData()
        {
            _submissions = new List<Submission>();
        }

        public IEnumerable<Submission> GetAll()
        {
            if (File.Exists(filePath) && File.ReadAllBytes(filePath).Length != 0)
            {
                using (Stream stream = File.Open(filePath, FileMode.Open))
                {
                    var binaryFormatter = new BinaryFormatter();
                    var otherList = (List<Submission>) binaryFormatter.Deserialize(stream);
                    return otherList;
                }
            }
            return new List<Submission>();
        }

        public void AddSubmission(Submission sub)
        {
            _submissions.Add(sub);
            using (Stream stream = File.Open(filePath, FileMode.Create))
            {
                var binaryFormatter = new BinaryFormatter();
                binaryFormatter.Serialize(stream, _submissions);
                stream.Close();
            }
        }

        public bool VerifyNewSubmission(string serialNumb)
        {
            foreach (var sub in GetAll())
            {
                if (serialNumb.Equals(sub.SerialNumb)) return false;
            }
            return true;
        }
    }
}
    

Assignment2/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Assignment2.Models;
using Microsoft.AspNetCore.Authorization;
using MyClassLibrary;


namespace Assignment2.Controllers
{

    public class SubmissionController : Controller
    {
        private ISerialNumbersData _serialNumbersData;
        private ISubmissionData _submissionData;

        public SubmissionController(ISerialNumbersData serialNumberData, ISubmissionData submissionData)
        {
            _serialNumbersData = serialNumberData;
            _submissionData = submissionData;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Index(Submission inputData)
        {           
            if (ModelState.IsValid && _serialNumbersData.VerifySerialNumber(inputData.SerialNumb) && _submissionData.VerifyNewSubmission(inputData.SerialNumb))
            {
                var submission = new Submission
                {
                    FirstName = inputData.FirstName,
                    SurName = inputData.SurName,
                    Email = inputData.Email,
                    PhoneNumb = inputData.PhoneNumb,
                    DateOfBirth = inputData.DateOfBirth,
                    SerialNumb = inputData.SerialNumb
                };
                _submissionData.AddSubmission(submission);
            }
            return View();
        }

        [HttpGet("admin/submissions")]
        public IActionResult AdminSubmissions()
        {
            if (_serialNumbersData.GetAll().Any())
            {
                ViewData["submissions"] = _submissionData.GetAll(); 
            }
            
            return View();
        }


        [HttpGet("admin/serialnumbers")]
        public IActionResult AdminSerialNumbers()
        {
            ViewData["serialnumbers"] = _serialNumbersData.GetAll();

            return View();
        }
    }
}

Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Assignment2</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Submission" asp-action="Index" class="navbar-brand">Submission</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Submission" asp-action="AdminSubmissions">Submissions</a></li>
                    <li><a asp-area="" asp-controller="Submission" asp-action="AdminSerialNumbers">Serial numbers</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Assignment2/Views/Submission/AdminSerialNumbers.cshtml
@*@{
    ViewData["serialnumbers"] = "SerialNumbers";
}*@

<h2>Serial numbers</h2>

<br />
<table style="width: 50%">
    <tr>
        <td><b>Serial number</b></td>
    </tr>
    @foreach (var serialNumber in ViewData["serialnumbers"] as List<string>)
    {
        <tr>
            <td>@serialNumber</td>
        </tr>      
    }
    
</table>

Assignment2/Views/Submission/AdminSubmissions.cshtml
@using MyClassLibrary

@*@{
    ViewData["submissions"] = "Submission";
}*@
<h2>Admin</h2>


<br/><table style="width: 80%">
    <tr>
        <td><b>First name</b></td>
        <td><b>Surname</b></td>
        <td><b>Email</b></td>
        <td><b>Phone number</b></td>
        <td><b>Date of birth</b></td>
        <td><b>Serial number</b></td>
    </tr>
         @foreach (var submission in ViewData["submissions"] as List<Submission>)
         {
             <tr>
                 <td>@submission.FirstName</td>
                 <td>@submission.SurName</td>
                 <td>@submission.Email</td>
                 <td>@submission.PhoneNumb</td>
                 <td>@submission.DateOfBirth</td>
                 <td>@submission.SerialNumb</td>
             </tr>
         }
</table>

Assignment2/Views/Submission/index.cshtml
@*@{
    ViewData["Title"] = "Submission";
    
}*@
@using Assignment2.Models
@using MyClassLibrary
@model MyClassLibrary.Submission
<h2>Submission</h2>
<form method="post" asp-controller="Submission" asp-action="Index">
    <div>
        <div>
            <input asp-for="FirstName" placeholder="First name" />
            <span asp-validation-for="FirstName"></span>

        </div><br />
        <div>
            <input asp-for="SurName" placeholder="Surname" />
            <span asp-validation-for="SurName"></span>
        </div><br />
        <div>
            <input asp-for="Email" placeholder="Email" />
            <span asp-validation-for="Email"></span>
        </div><br />
        <div>
            <input asp-for="PhoneNumb" placeholder="Phone number" />
            <span asp-validation-for="PhoneNumb"></span>
        </div><br />
        <div>
            <input asp-for="DateOfBirth" />
            <span asp-validation-for="DateOfBirth"></span>
        </div><br />
        <div>
            <input asp-for="SerialNumb" placeholder="Serial key" />
            <span asp-validation-for="SerialNumb"></span>
        </div><br />
        <div>
            <input type="Submit" name="submit" value="Submit" />
        </div><br/>
    </div>
</form>